### ISSUE TITLE
Error while trying to execute skyring single node

### ISSUE THREAD

**Issue by leandrocurioso** [esatterwhite/skyring#105]
## The command

```bash
node ./index.js --channel:port=3455 --seeds='localhost:3455'
```
### The error
```javascript
{"level":30,"time":1631814191501,"pid":31780,"hostname":"ubuntu","name":"skyring","name":"skyringnode_modules:skyring//server:node","msg":"contacting seed nodes [\"127.0.0.1\",\"127.0.0.1:3455\",\"127.0.0.1:3456\"]"}
// Illegal instruction (core dumped)
```

**My index.js file is:**
```javascript
const Skyring = require('skyring');

const server = new Skyring();

const port = process.env.PORT || 4001

function onSignal() {
  server.close(() => {
    console.log('shutting down');
  });
}

console.log(port);
server.listen(port, (err) => {
  if (err) throw err;
  console.log(`Skyring listening at %s', 'http://127.0.0.1:${port}`);
});

process.once('SIGINT', onSignal);
process.once('SIGTERM', onSignal);
```

I have no idea what can be happening, the strange thing is that runs normally in my local machine but not in my VPS server.

**_I'm using:
VPS: Ubuntu Server 20.04
NodeJS Version: v14.17.6
Node Gyp: v8.2.0
 CPU: Intel(R) Xeon(R) CPU  X5670 @ 2.93GHz_**

**Comment by esatterwhite** [comment]
thans for the report. looking into it. skyring@10.2.0 I presume?

**Comment by esatterwhite** [comment]
based on the log message

```
contacting seed nodes [\"127.0.0.1\",\"127.0.0.1:3455\",\"127.0.0.1:3456\"]"}
```
It looks like its still configured to contact a secondary node running on port `3456`

**Comment by esatterwhite** [comment]
@leandrocurioso would you be able to attache the core file? A lot of machines have a core file size of zero so it may not be generatied

```bash
ulimit -c
```

if that is `0` they won't be generated.

common locations for core files would be just the working directory from the process. or `/cores`

**Comment by leandrocurioso** [comment]
> @leandrocurioso would you be able to attache the core file? A lot of machines have a core file size of zero so it may not be generatied
> 
> ```shell
> ulimit -c
> ```
> 
> if that is `0` they won't be generated.
> 
> common locations for core files would be just the working directory from the process. or `/cores`

After some research I found that some old CPU are not architecture compatible with new  instructions and  will exit the program execution with the message "Illegal instruction (core dumped)". I was using a crappy VPS provider so I change it to Digital Ocean and everything went normal.

Thanks for the help!
