### ISSUE TITLE
Document minimum/maximum allowed `timeout` value

### ISSUE THREAD

**Issue by camlegleiter** [esatterwhite/skyring#18]
It's not explicitly documented in either the API or README/Module docs, but given that `skyring` uses `setTimeout` internally for managing timers within each node, there is a minimum/maximum timeout allowed for `setTimeout`. From the [NodeJS docs](https://nodejs.org/docs/latest-v10.x/api/timers.html#timers_settimeout_callback_delay_args):

> When `delay` is larger than `2147483647` or less than `1`, the `delay` will be set to `1`.

It may be worth noting this limitation in the API and README, and/or potentially updating the timer validator to [check for this more explicitly](https://github.com/esatterwhite/skyring/blob/master/lib/server/api/validators/timer.js#L13) to avoid unexpected behavior.

**Comment by esatterwhite** [comment]
The docs do say that setTimeout is used.
What was unexpected exactly?

**Comment by camlegleiter** [comment]
Not to nitpick, but the docs _imply_ usage of `setTimeout`:
> A distributed reliable timer service providing _similar_ functionality to using `setTimeout`.

The "unexpected" part comes from setting timeouts larger than the maximum allowed by `setTimeout`, which means the callback is invoked immediately. In my case, this caused certain workflow state in my application to be considered "timed out" far in advance of what was anticipated when I assumed a large default value for a timeout. I've since lowered this default to something within the maximum possible, but it took me a while to discover the reason for why the callback was invoked immediately.

**Comment by esatterwhite** [comment]
fair enough. if you want to make a PR to update the validator to validate the upper bound - that works for me.
