### ISSUE TITLE
Timers getting reset on double recovery

### ISSUE THREAD

**Issue by Iaskebba** [esatterwhite/skyring#22]
I am using Mongo as a persistent backend. This issue is more of an issue in Kubernetes where the nodes instantly will come back online in under a second if it is killed.

1. If a node dies sometimes the rebalance will not occur at all (rare). But when the node comes back online it will pick up the timer at the correct timing if no rebalancing occurred.

2. If a node dies and rebalancing occurs and the original node does not come back up the timer will still be accurate on the node that rebalanced it.

The issue that occurs is when a node dies and rebalancing occurs, if the original node comes back online the timer will be rescheduled back to the original node and at this point the timer will be reset back to 0 and go through the entire timeout again.

**Comment by Iaskebba** [comment]
Further investigation shows that even if the rebalance function was turned off completely the error still comes from passing timers off more than once. If the rebalance function is completely commented out and the node shuts down gracefully the timer gets successfully passed on. If the new node then gracefully shutsdown it will pass the timers off but they will all be reset back to 0.

**Comment by esatterwhite** [comment]
so basically a one node crashes and comes back while the rebalance from the crash is still happening?
