### ISSUE TITLE
Timers lost on Shutdown occasionally

### ISSUE THREAD

**Issue by Iaskebba** [esatterwhite/skyring#24]
Timers will sometimes be lost on shutdown. I am using Mongo for persistency. The timers are never lost in the rebalance process and only ever lost in the shutdown. To reproduce this: 

1. Run 3 nodes then send ~100 timers at the cluster
2. Check that all timers are present in Mongo
3. Send SIGTERM to one node
4. After a complete shutdown check Mongo for loss of timers (Sometimes in trials it would be correct but it was not consistent)
5. Restart the node back up and check Mongo for correct rebalance

Repeat this process any amount of times and with any node in the cluster. A loss of timers from shutting down will be seen.

Rebalance from Recovery NEVER had errors in a script that constantly repeated this process, only shutdown had loss of timers. The more timers the node held the more profound this loss was from shutting down. I know the node is completely shutting down gracefully as I completely removed the SIGKILL timeout and I can see the logs showing that the node exited properly. I can also see the node successfully logging that it has processed the correct amount of rebalances while it is shutting down.

**Comment by Iaskebba** [comment]
If this.disconnect(cb) gets commented out the node won't exit but the timers never drop. I believe a race condition is occurring here and the node is disconnecting too soon. I'm looking more into it

**Comment by esatterwhite** [comment]
Ya. Sounds like a race with the last write ack from mongo

**Comment by Iaskebba** [comment]
I agree that there still is a race condition that exists with the mongo storage. I'm not sure how to find it however. I can only reproduce this bug in Kubernetes using a large amount of requests and killing the node during this chain. Sometimes I will get +1 extra timer which I assume is from timers firing as they are trying to transfer them off (more acceptable explanation). Other times I will lose a large amount of timers from killing a node with no clear explanation as to why. And even rarer I will receive the following error messages stating that a timer with an id already exists. I think the post you made in the PR about the driver could be promising and I will try to follow up on that.
`2018-11-30T00:52:15.418Z skyring:error Error: Timer with id 231fcc23-3057-476a-9d17-7499e6e057dd already exists
2018-11-30T00:52:15.419Z skyring:error Error: Timer with id 226d3015-4a3b-465d-a58c-2c74de221b42 already exists`
