### ISSUE TITLE
Use firebase as backend

### ISSUE THREAD

**Issue by amitrjain** [esatterwhite/skyring#65]
https://www.npmjs.com/package/firebase-down
how to use firebase-down instead of mongo-down?

**Comment by esatterwhite** [comment]
@amitrjain This package looks a little old and implements abstract-level down v2

It expects you to pass the backend as a second argument
```javascript
var firebaseApp = firebase.initializeApp(config)
var firebaseDown = FirebaseDOWN(firebaseApp)

var db = levelup('level', {db: firebaseDown})
```

Rather than passing the backend as the first argument with the current version of abstract-level down

```javascript
var levelup = require('levelup')
var leveldown = require('leveldown')
 
// 1) Create our store
var db = levelup(leveldown('./mydb'))
```

this doesn't look compatible in its current state.

**Comment by amitrjain** [comment]
thank you !
